blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/Piyushiitk24/virtuallab-control-systems/discussions
    about: Ask questions and share ideas with the community
  - name: 📧 Direct Contact
    url: mailto:piyushiitk24@gmail.com
    about: For partnerships, collaborations, and private inquiries
  - name: 📖 Documentation
    url: https://github.com/Piyushiitk24/virtuallab-control-systems/blob/main/README.md
    about: Check our comprehensive documentation first
